name: Actualizar catálogo

on:
  schedule:
    - cron: '0 6 * * *'  # Todos los días a las 6:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install requests beautifulsoup4

      - name: Ejecutar script de scraping
        run: python actualizar_catalogo.py

      - name: Commit y push del archivo actualizado
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add productos.json || echo "No hay cambios para commitear"
          git commit -m "🛒 Catálogo actualizado automáticamente" || echo "Nada para commitear"
          git push https://x-access-token:${{ secrets.PUSH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
